### ISSUE TITLE
Paralelnost verzí

### ISSUE THREAD

**Issue by Katkabukacova** [josefmana/nbd_paraREL#1]
Ještě doplňuju hypotézy, které má studentka nachystané k exekutivním funkcím:
**4.1.	Výzkumné otázky a hypotézy**
Otázky směřují k posouzení ekvivalence mezi verzemi testové baterie v oblasti exekutivních funkcí u dětí.
Otázka č. 1: Jaká je korelace mezi paralelními formami A a B NB-D v oblasti exekutivních funkcí?
Otázka č. 2: Bude mezi průměrnými hrubými skóry pro verzi A a B NB-D v oblasti exekutivních funkcí významný rozdíl?
Hypotézy dále zpřesňují výzkumné otázky a zmiňují, v jakých situacích bude nebo nebude daná hypotéza přijata.
Hypotéza č. 1: Reliabilita paralelních forem jednotlivých subtestů domény exekutivních funkcí verze A a verze B NB-D dosáhne korelace minimálně r = .45, se statistickou signifikancí na úrovni p = .05.
Hypotéza č. 2: Průměrný rozdíl hrubých skórů mezi verzí A a verzí B NB-D v jednotlivých subtestech domény exekutivních funkcí bude statisticky nevýznamný na úrovni p = .05.

**Comment by josefmana** [comment]
Hypotézy se vztahují k fenoménům v populaci, ne k výsledkům testu, já bych jí dal, kdybych byl oponentem :-D Každopádně, výsledky dodány, korelace + rozdílová a popisná statistika ve složce "/tabs", korelace navíc vizualizovány ve složce "/figs" :-)
